# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typ0 < Formula
  desc "A CLI typing practice tool"
  homepage "https://github.com/TusharIbtekar/go-typ0"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.1.0/go-typ0_Darwin_x86_64.tar.gz"
      sha256 "b5b2684d16c84d53011ca7dd3526b61458cff4a977f57ea9fce08a811e70ec5f"

      def install
        bin.install "typ0"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.1.0/go-typ0_Darwin_arm64.tar.gz"
      sha256 "3eec6895be3d33ff980df3f0505a04710c05bb4f489da95c93273a2fffdd2d03"

      def install
        bin.install "typ0"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.1.0/go-typ0_Linux_x86_64.tar.gz"
      sha256 "c112ab1913a20858841309d9b3844d2135c1e26b240957302b84faef57582be8"
      def install
        bin.install "typ0"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.1.0/go-typ0_Linux_arm64.tar.gz"
      sha256 "ee356aec612762745fba04c3e4b83f535fe4cb3552f69a7b2d2948209e488d95"
      def install
        bin.install "typ0"
      end
    end
  end
end
