# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typ0 < Formula
  desc "A CLI typing practice tool"
  homepage "https://github.com/TusharIbtekar/go-typ0"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.0.0/go-typ0_Darwin_x86_64.tar.gz"
      sha256 "86ecbdbe5ea14a4788ea1acb67dcdfea061e409934b0981582665eb7e156c942"

      def install
        bin.install "typ0"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.0.0/go-typ0_Darwin_arm64.tar.gz"
      sha256 "c37842bf946e981b72b83ef753e7fb3d3bfbe1297c13f81ee39a1409f4fc594f"

      def install
        bin.install "typ0"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.0.0/go-typ0_Linux_x86_64.tar.gz"
      sha256 "6cdaf19bd192587167d9ec7c36176bc30838d560834f6e218f974a0bbd31db5b"
      def install
        bin.install "typ0"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.0.0/go-typ0_Linux_arm64.tar.gz"
      sha256 "1e38eddc443b1bb02b265864061dd128633a1fe622717ae6a78bb41fb31e7553"
      def install
        bin.install "typ0"
      end
    end
  end
end
