# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typ0 < Formula
  desc "A CLI typing practice tool"
  homepage "https://github.com/TusharIbtekar/go-typ0"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.1.1/go-typ0_Darwin_x86_64.tar.gz"
      sha256 "5feebeca8211115a5fe1b145074464826de32be0015406c3fa533aef56bfa2a2"

      def install
        bin.install "typ0"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.1.1/go-typ0_Darwin_arm64.tar.gz"
      sha256 "bbbbd9fe0e22ec6e1629073011d1707421a41d2c59fed751792580aac10baeb8"

      def install
        bin.install "typ0"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.1.1/go-typ0_Linux_x86_64.tar.gz"
      sha256 "b63557cea8e6159b668aca41d6093d2e80d2e482ff971d3f88d645040b7ca094"
      def install
        bin.install "typ0"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/TusharIbtekar/go-typ0/releases/download/v1.1.1/go-typ0_Linux_arm64.tar.gz"
      sha256 "a3212e0d348ff7267d88413d1a8f3148975addb2a4c238ba01a53aea2b281baa"
      def install
        bin.install "typ0"
      end
    end
  end

  def post_install
    puts "🏁 Welcome to Typ0!"
    puts "Start typing: typ0 race"
    puts "Show help: typ0 --help"
    puts ""
    puts "Happy typing! 🎯"
  end
end
